package com.techvestai.project.enums;

public enum AuditEventType {
    APPLICATION_SUBMITTED,
    DOCUMENT_VALIDATION_RESULT,
    CREDIT_SCORE_COMPUTED,
    RECOMMENDATION_PRODUCED,
    FAIRNESS_EVALUATION_COMPLETED,
    FINAL_DECISION_RECORDED,
    DESERIALISATION_FAILURE
}
