spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/techvest_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    jwt:
      secret: yourverylongandsecurejwtsecretkeyforthisapplicationthatshouldbemorethan256bitslong
      expiration: 3600000 # 1 hour

server:
  port: 8080
